### PR TITLE
Add cwarwicker/moodle-tool_ribbons plugin with moodle_4.4 tag to admin/tool/ribbons as a submodule.

### PR DESCRIPTION
**Pull request by ctam**
See GHA [here](https://github.com/ctam/moodle/actions/runs/10950324696).

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208356848947589

### CODE REVIEW

**Comment by ctam** [comment]
GHA generated 11 errors [here](https://github.com/ctam/moodle/actions/runs/10950324696).

**Review by stopfstedt — DISMISSED** [review]

**Comment by stopfstedt** [comment]
i had a look at the build errors, and there are two that are related to this plugin, but they appear several times

`Debugging: Callback before_standard_html_head in tool_ribbons component should be migrated to new hook callback for core\hook\output\before_standard_head_html_generation`

and

`Debugging: Callback before_standard_top_of_body_html in tool_ribbons component should be migrated to new hook callback for core\hook\output\before_standard_top_of_body_html_generation`

i see a clear upgrade path with minimal effort here, will put in a ticket and fix with the upstream maintainers. sit tight.

**Comment by stopfstedt** [comment]
upstream ticket: https://github.com/cwarwicker/moodle-tool_ribbons/issues/10

upstream pull request: https://github.com/cwarwicker/moodle-tool_ribbons/pull/11

**Comment by stopfstedt** [comment]
@ctam there's a new release of Ribbons as of this morning that includes the fix for these deprecation warnings.

https://github.com/cwarwicker/moodle-tool_ribbons/releases/tag/moodle_4.5

the new release tag is labeled ~~`moodle_4.5 `~~ _edit:_ `moodle_4.4`

please update the PR, thanks.

**Comment by ctam** [comment]
Passed all GHA tests (here)[https://github.com/ctam/moodle/actions/runs/11073510331].

**Review by stopfstedt — APPROVED** [review]
LGTM

**Pull request merged**
