### PR TITLE
Updated mod_customercert to v4.3.3

### PR DESCRIPTION
**Pull request by lbailey-ucsf**
Pertains to task [T-1767 in Asana](https://app.asana.com/0/0/1208571193901422/f).

### CODE REVIEW

**Comment by lbailey-ucsf** [comment]
@ctam how do you get the workflow to run on this branch?

**Comment by ctam** [comment]
Try this, (given you're on your branch, `T-1767/UCSFCLE_403/update-mod_customcert`)
```
git fetch --all
git rebase origin/UCSFCLE_403_STABLE
git push --force
```
My `origin` is `https://github.com/ucsf-education/moodle`.

**Comment by lbailey-ucsf** [comment]
> Try this, (given you're on your branch, `T-1767/UCSFCLE_403/update-mod_customcert`)
> 
> ```
> git fetch --all
> git rebase origin/UCSFCLE_403_STABLE
> git push --force
> ```
> 
> My `origin` is `https://github.com/ucsf-education/moodle`.

@ctam The workflow ran on my fork. It's not running here for some reason. Not sure what you're suggesting those git commands are gonna do in regard to getting tests to run here. Also, my origin is my fork.

**Comment by ctam** [comment]
LOL. I got confused with M4.4 again! Sorry. That was an attempt to pull Jon's change into your branch.  Please forget it. Without Jon's change, this PR is not going to run the workflow.  But looks like your tests have already been run [here](https://github.com/lbailey-ucsf/moodle/actions/runs/11470401076) and they are all green.  So, this PR is ready for review!

**Review by ctam — APPROVED** [review]
lgtm

**Pull request merged**
