### PR TITLE
Update Quiz Archive plugin to v4.5-r1.

### PR DESCRIPTION
**Pull request by ctam**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208571197277222

### CODE REVIEW

**Comment by lbailey-ucsf** [comment]
I don't see any indication that tests ran.

**Comment by ctam** [comment]
Tests were run [here](https://github.com/ctam/moodle/actions/runs/11481390046/job/31951942453). We do not have the PR trigger in the 403 stable branch yet. 

All green tests. Ready for review.

**Review by lbailey-ucsf — COMMENTED** [review]
Per discussion yesterday, should @mirleu review and merge? All that needs to be reviewed is making sure tests ran successfully and our standard practices have been followed, e.g. adding the tag to .gitmodules if necessary, placing .gitmodules contents in alpha order, etc.

LGTM.

**Review by mirleu — APPROVED** [review]
LGTM

**Pull request merged**
