### PR TITLE
Added mod/checklist master 4.1.0.2

### PR DESCRIPTION
**Pull request by lbailey-ucsf**
The UAT team needs to review this PR before getting the go-ahead to merge. It's currently failing the following behat scenario in my dev environment:

```
001 Scenario: A teacher can link to a course or a URL, but not both # /var/www/html/mod/checklist/tests/behat/course_link.feature:33
      And the "linkcourseid" "field" should be disabled             # /var/www/html/mod/checklist/tests/behat/course_link.feature:38
        The attribute "disabled" should be set but is not
```

### CODE REVIEW

**Comment by mirleu** [comment]
@ctam @lbailey-ucsf in this case the .gitmodules file has new updates not included in this request. Should I request changes or approve and then Leon to fix the merge conflict?

**Comment by lbailey-ucsf** [comment]
> @ctam @lbailey-ucsf in this case the .gitmodules file has new updates not included in this request. Should I request changes or approve and then Leon to fix the merge conflict?

I vote the latter. See what carson says.

**Comment by ctam** [comment]
Ha! This is a good one. @mirleu, how do you know there will be a merge conflict already? Did you check it in the command line?
Normally, I think it should go back to the developer to do a `git rebase` and resolve all the conflicts, especially if the code change is complex. But in this case, it's just a couple of line changes in the `.gitmodules` file, so I don't think it matters. But if you're asking for some policy, yeah, it should go back to the developer before approving it. 🙂

**Review by mirleu — APPROVED** [review]
lgtm

**Comment by mirleu** [comment]
> Ha! This is a good one. @mirleu, how do you know there will be a merge conflict already? Did you check it in the command line? Normally, I think it should go back to the developer to do a `git rebase` and resolve all the conflicts, especially if the code change is complex. But in this case, it's just a couple of line changes in the `.gitmodules` file, so I don't think it matters. But if you're asking for some policy, yeah, it should go back to the developer before approving it. 🙂

Turns out there was no merge conflict after I approved so I merged. I realized I was thinking of the M4.3 .gitmodules file but this is for M4.4. Good to know the process for next time. Thanks everyone!

**Pull request merged**
