### PR TITLE
Push on pull_request_target

### PR DESCRIPTION
**Pull request by ctam**

### CODE REVIEW

**Comment by ctam** [comment]
Hey @jrjohnson and @lbailey-ucsf, this [pull_request_target](https://runs-on.com/github-actions/pull-request-vs-pull-request-target/) trigger looks promising.  It says, "it runs in the context of the base repository." Can we merge this and see if it works?

**Comment by jrjohnson** [comment]
Changing the type isn't quite enough. You also need to change the checkout action to checkout the right code, by default it checks out the base branch (not your changes). It's also a bit of a foot gun because it really is designed to do things that don't require checking out the code (like commenting on a PR).

**Comment by lbailey-ucsf** [comment]
@jrjohnson @ctam @mirleu 

Can we move this to its own workflow for separation of concerns reasons? 

The file is push.yml. It's not far fetched to think we would want different actions to happen on push (deploy to stage) vs pull request (run acceptance tests and security scans). Also, seems like less of a maintenance burden to leave the Moodle core workflow as is and make our customization separately. 

There's also the idea of using forks as an extension of the dev environment. For one,  maybe we'd want to disincentive developers from turning off actions entirely because either certain actions take too long to run or tokens need to be managed unnecessarily. 

What are the cons?

**Comment by ctam** [comment]
The more I think about this, the more I want to get rid of the private repo, and then we do not need to add these triggers and keep things simple.

But to reply to your comment, @lbailey-ucsf. I think the big con is it will be too easy for us to miss out on any changes or improvements in the Moodle core workflow. Keeping it in the same file will force us to evaluate the merge and adopt the latest improvement from Moodle HQ. 

Unfortunately, this `pull_request_target` does not seem to serve our purpose (to check out private repos). I am going to close this PR without a merge if there's no objection.

**Comment by ctam** [comment]
This will not work. Closing.

**Pull request closed without merging**
