### PR TITLE
Add ncstate-delta/moodle-mod_zoom with v5.2.4 tag to mod/zoom as a git submodule

### PR DESCRIPTION
**Pull request by ctam**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208451304753727
  - https://app.asana.com/0/0/1208571197277217

### CODE REVIEW

**Review by mirleu — APPROVED** [review]
LGTM

**Comment by ctam** [comment]
Inherited [12 PHPUnit test errors](https://github.com/ctam/moodle/actions/runs/11409945974) from the [STABLE branch](https://github.com/ucsf-education/moodle/actions?query=branch%3AUCSFCLE_404_STABLE).

**Comment by ctam** [comment]
Rebased. Running tests [here](https://github.com/ctam/moodle/actions/runs/11468546262).

**Comment by ctam** [comment]
Re-ran [Core / PHPUnit tests](https://github.com/ucsf-education/moodle/actions/runs/11484893864/job/31963745142?pr=95). All passed. Ready for review.

**Comment by ctam** [comment]
Hey @mirleu, could you do another review and merge it if it looks good to you? Thanks!

**Review by mirleu — APPROVED** [review]
LGTM

**Comment by mirleu** [comment]
> This branch has conflicts that must be resolved

@ctam I approved but there seems to be conflicts and it's not allowing me to merge.

**Comment by lbailey-ucsf** [comment]
> > This branch has conflicts that must be resolved
> 
> @ctam I approved but there seems to be conflicts and it's not allowing me to merge.

I resolved the conflict but now tests are running again. @ctam @mirleu your call on when to merge. I should note that I did not put the submodules in order when resolving the conflict.

**Pull request merged**
