### PR TITLE
Add the tool/externaltaskmonitor plugin to Moodle 4.4

### LINKED ISSUE #52: Add tool_externaltaskmonitor plugin to Moodle 4.4
https://github.com/ucsf-education/tool_externaltaskmonitor

### PR DESCRIPTION
**Pull request by ctam**
This PR includes changes to `push.yml` that enable GHA in submodules.

### CODE REVIEW

**Comment by lbailey-ucsf** [comment]
why not just delete unwanted lines in push.yml instead of commenting them out?

**Comment by ctam** [comment]
Good question. 

I do want to preserve the general structure of the [original file](https://github.com/moodle/moodle/blob/v4.4.3/.github/workflows/push.yml) from Moodle HQ and also be able to insert my comments regarding why we want to disable Grunt in the submodules and PostgreSQL testing in the file. 

My concern is that a developer would come in and start adding new changes to the file without knowing that all these cool features have already been implemented in Moodle HQ's repo. As time goes on, this file may become unrecognizable that we start adding new changes and make it further deviate from the Moodle HQ's code. I didn't think it's practical for a developer to always check the commit log before coding for a feature. In this case say, adding support for PostgreSQL.

If there is a better way to ensure that, I am all ears.

**Review by lbailey-ucsf — APPROVED** [review]
i'd suggest removing commented out lines of code before committing.

**Comment by ctam** [comment]
Thanks for your comment. 

I think I will leave them there for now. I really don't want to see a developer start coding his own way of setting up, say, a different PostgreSQL image while they could've simply used `m4nu56/PostgreSQL`, the one Moodle HQ uses.

**Pull request merged**
